-- begin TAXICONTROL_TAXI
create unique index IDX_TAXICONTROL_TAXI_UNIQ_DRIVER_PHONE on TAXICONTROL_TAXI (DRIVER_PHONE)^
-- end TAXICONTROL_TAXI
-- begin TAXICONTROL_AUTO_MODEL
alter table TAXICONTROL_AUTO_MODEL add constraint FK_TAXICONTROL_AUTO_MODEL_ON_VENDOR foreign key (VENDOR_ID) references TAXICONTROL_AUTO_VENDOR(ID)^
create index IDX_TAXICONTROL_AUTO_MODEL_ON_VENDOR on TAXICONTROL_AUTO_MODEL (VENDOR_ID)^
-- end TAXICONTROL_AUTO_MODEL
-- begin TAXICONTROL_ROUTE
alter table TAXICONTROL_ROUTE add constraint FK_TAXICONTROL_ROUTE_ON_TAXI foreign key (TAXI_ID) references TAXICONTROL_TAXI(ID)^
create index IDX_TAXICONTROL_ROUTE_ON_TAXI on TAXICONTROL_ROUTE (TAXI_ID)^
-- end TAXICONTROL_ROUTE
