alter table TAXICONTROL_AUTO_MODEL add constraint FK_TAXICONTROL_AUTO_MODEL_ON_VENDOR foreign key (VENDOR_ID) references TAXICONTROL_AUTO_VENDOR(ID);
create index IDX_TAXICONTROL_AUTO_MODEL_ON_VENDOR on TAXICONTROL_AUTO_MODEL (VENDOR_ID);
