-- begin TAXICONTROL_TAXI
create unique index IDX_TAXICONTROL_TAXI_UK_DRIVER_PHONE on TAXICONTROL_TAXI (DRIVER_PHONE) where DELETE_TS is null ^
-- end TAXICONTROL_TAXI
-- begin TAXICONTROL_AUTO_MODEL
alter table TAXICONTROL_AUTO_MODEL add constraint FK_TAXICONTROL_AUTO_MODEL_ON_VENDOR foreign key (VENDOR_ID) references TAXICONTROL_AUTO_VENDOR(ID)^
create index IDX_TAXICONTROL_AUTO_MODEL_ON_VENDOR on TAXICONTROL_AUTO_MODEL (VENDOR_ID)^
-- end TAXICONTROL_AUTO_MODEL
